### ISSUE TITLE
MEET Page not found when login the default account

### ISSUE THREAD

**Issue by czwstc** [cloudy-sfu/Clixove-Library#2]
When I was testing, I used the default username and password to log in (cloudy cl210186). 
I got the following false alarm:

![image](https://user-images.githubusercontent.com/15552128/111913031-3b0fe100-8aa7-11eb-9fb6-a4a5419fe326.png)

**Comment by cloudy-sfu** [comment]
Fixed in https://github.com/cloudy-sfu/Clixove-Library/commit/5255d5a0abfeb2063ceb140498bd9cc06b46c65f
